export const SignatureTypes = {
    DELETE_SIGNATURE_ACTION: 'DELETE_SIGNATURE_ACTION',
    MODIFY_SIGNATURE_ACTION: 'MODIFY_SIGNATURE_ACTION',
    UPLOAD_SIGNATURE_ERROR: 'UPLOAD_SIGNATURE_ERROR',
    UPLOAD_SIGNATURE_SUCCESS: 'UPLOAD_SIGNATURE_SUCCESS',
    UPLOAD_SIGNATURE_LOAD: 'UPLOAD_SIGNATURE_LOAD',
    ADD_RESPONSE:"ADD_RESPONSE",
    ADD_SIGNATURE_ACTION: "ADD_SIGNATURE_ACTION",
    DELETE_SIGNATURE_ACTION:"DELETE_SIGNATURE_ACTION",
}   