export const PdvTypes = {
    MODIFY_PDV: 'MODIFY_PDV',
    DELETE_PDV: 'DELETE_PDV',
    SUCCESS_ACTION_PDV:'SUCCESS_ACTION_PDV',
    LOADING_ACTION_PDV:'LOADING_ACTION_PDV',
    ERROR_ACTION_PDV:'ERROR_ACTION_PDV',
    VALIDATION_ERROR_ACTION_PDV:'VALIDATION_ERROR_ACTION_PDV', 
    LAOD_FILE_ACTION:'LAOD_FILE_ACTION',
    IMPORT_FILE_SUCCESS:'IMPORT_FILE_SUCCESS',
    IMPORT_FILE_ERROR:'IMPORT_FILE_ERROR',
  ADD_PDV: 'ADD_PDV',
    SEARCH_PDV: 'SEARCH_PDV',
  };